# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


cities = City.create([
	{state: 'CA', name: 'Los Angeles'},
	{state: 'CA', name: 'San Francisco'},
	{state: 'WA', name: 'Seattle'},
	{state: 'NY', name: 'New York City'}
])


# neighborhood seeds
neighborhoods = Neighborhood.create([
	#NYC
	#Manhattan
	{name: 'Alphabet City', city_id: 4, borough: 'Manhattan'},
	{name: 'Battery Park City', city_id: 4, borough: 'Manhattan'},
	{name: 'Carnegie Hill', city_id: 4, borough: 'Manhattan'},
	{name: 'Chelsea', city_id: 4, borough: 'Manhattan'},
	{name: 'Chinatown', city_id: 4, borough: 'Manhattan'},
	{name: 'East Harlem', city_id: 4, borough: 'Manhattan'},
	{name: 'East Village', city_id: 4, borough: 'Manhattan'},
	{name: 'Financial District', city_id: 4, borough: 'Manhattan'},
	{name: 'Flatiron District', city_id: 4, borough: 'Manhattan'},
	{name: 'Gramercy Park', city_id: 4, borough: 'Manhattan'},
	{name: 'Greenwhich Village', city_id: 4, borough: 'Manhattan'},
	{name: 'Harlem', city_id: 4, borough: 'Manhattan'},
	{name: 'Hell\'s Kitchen', city_id: 4, borough: 'Manhattan'},
	{name: 'Inwood', city_id: 4, borough: 'Manhattan'},
	{name: 'Kips Bay', city_id: 4, borough: 'Manhattan'},
	{name: 'Lincoln Square', city_id: 4, borough: 'Manhattan'},
	{name: 'Lower East Side', city_id: 4, borough: 'Manhattan'},
	{name: 'Manhattan Valley', city_id: 4, borough: 'Manhattan'},
	{name: 'Midtown East', city_id: 4, borough: 'Manhattan'},
	{name: 'Midtown West', city_id: 4, borough: 'Manhattan'},
	{name: 'Morningside Heights', city_id: 4, borough: 'Manhattan'},
	{name: 'Murray Hill', city_id: 4, borough: 'Manhattan'},
	{name: 'NoLita/Little Italy', city_id: 4, borough: 'Manhattan'},
	{name: 'Roosevelt Island', city_id: 4, borough: 'Manhattan'},
	{name: 'SoHo', city_id: 4, borough: 'Manhattan'},
	{name: 'Tribeca', city_id: 4, borough: 'Manhattan'},
	{name: 'Upper East Side', city_id: 4, borough: 'Manhattan'},
	{name: 'Upper West Side', city_id: 4, borough: 'Manhattan'},
	{name: 'Washington Heights', city_id: 4, borough: 'Manhattan'},
	{name: 'West Village', city_id: 4, borough: 'Manhattan'},
	#Bronx
	{name: 'Baychester/Co-op City', city_id: 4, borough: 'Bronx'},
	{name: 'Bedford Park', city_id: 4, borough: 'Bronx'},
	{name: 'Belmont', city_id: 4, borough: 'Bronx'},
	{name: 'Bronxdale', city_id: 4, borough: 'Bronx'},
	{name: 'CastleHill', city_id: 4, borough: 'Bronx'},
	{name: 'City Island', city_id: 4, borough: 'Bronx'},
	{name: 'Concourse Village/Grand Concourse/Morrisania', city_id: 4, borough: 'Bronx'},
	{name: 'Country Club', city_id: 4, borough: 'Bronx'},
	{name: 'Fieldston', city_id: 4, borough: 'Bronx'},
	{name: 'Fordham', city_id: 4, borough: 'Bronx'},
	{name: 'Hunts Point', city_id: 4, borough: 'Bronx'},
	{name: 'Kingsbridge', city_id: 4, borough: 'Bronx'},
	{name: 'Kingsbridge Heights', city_id: 4, borough: 'Bronx'},
	{name: 'Melrose', city_id: 4, borough: 'Bronx'},
	{name: 'Morris Heights', city_id: 4, borough: 'Bronx'},
	{name: 'Morris Park', city_id: 4, borough: 'Bronx'},
	{name: 'Mott Haven', city_id: 4, borough: 'Bronx'},
	{name: 'Parkchester', city_id: 4, borough: 'Bronx'},
	{name: 'Pelham Bay', city_id: 4, borough: 'Bronx'},
	{name: 'Pelham Gardens', city_id: 4, borough: 'Bronx'},
	{name: 'Pelham Parkway', city_id: 4, borough: 'Bronx'},
	{name: 'Port Morris', city_id: 4, borough: 'Bronx'},
	{name: 'Riverdale', city_id: 4, borough: 'Bronx'},
	{name: 'Soundview', city_id: 4, borough: 'Bronx'},
	{name: 'Throgs Neck', city_id: 4, borough: 'Bronx'},
	{name: 'Tremont', city_id: 4, borough: 'Bronx'},
	{name: 'University Heights', city_id: 4, borough: 'Bronx'},
	{name: 'Wakefield', city_id: 4, borough: 'Bronx'},
	{name: 'Williamsbridge', city_id: 4, borough: 'Bronx'},
	{name: 'Woodlawn', city_id: 4, borough: 'Bronx'},

	#Brooklyn
	{name: 'Bath Beach', city_id: 4, borough: 'Brooklyn'},
	{name: 'Bay Ridge', city_id: 4, borough: 'Brooklyn'},
	{name: 'Bedford-Stuyvesant', city_id: 4, borough: 'Brooklyn'},
	{name: 'Bensonhurst', city_id: 4, borough: 'Brooklyn'},
	{name: 'Bergen Beach', city_id: 4, borough: 'Brooklyn'},
	{name: 'Boerum Hill', city_id: 4, borough: 'Brooklyn'},
	{name: 'Borough Park', city_id: 4, borough: 'Brooklyn'},
	{name: 'Brighton Beach', city_id: 4, borough: 'Brooklyn'},
	{name: 'Brooklyn Heights', city_id: 4, borough: 'Brooklyn'},
	{name: 'Brownsville', city_id: 4, borough: 'Brooklyn'},
	{name: 'Bushwick', city_id: 4, borough: 'Brooklyn'},
	{name: 'Canarsie', city_id: 4, borough: 'Brooklyn'},
	{name: 'Clinton Hill', city_id: 4, borough: 'Brooklyn'},
	{name: 'Carroll Gardens', city_id: 4, borough: 'Brooklyn'},
	{name: 'Cobble Hill', city_id: 4, borough: 'Brooklyn'},
	{name: 'Coney Island', city_id: 4, borough: 'Brooklyn'},
	{name: 'Crown Heights', city_id: 4, borough: 'Brooklyn'},
	{name: 'Cypress Hills', city_id: 4, borough: 'Brooklyn'},
	{name: 'Downtown Brooklyn', city_id: 4, borough: 'Brooklyn'},
	{name: 'DUMBO/Vinigar Hill', city_id: 4, borough: 'Brooklyn'},
	{name: 'Dyker Heights', city_id: 4, borough: 'Brooklyn'},
	{name: 'East New York', city_id: 4, borough: 'Brooklyn'},
	{name: 'Flatbush', city_id: 4, borough: 'Brooklyn'},
	{name: 'Flatlands', city_id: 4, borough: 'Brooklyn'},
	{name: 'Fort Greene', city_id: 4, borough: 'Brooklyn'},
	{name: 'Gerritsen Beach', city_id: 4, borough: 'Brooklyn'},
	{name: 'Gowanus', city_id: 4, borough: 'Brooklyn'},
	{name: 'Gravesend', city_id: 4, borough: 'Brooklyn'},
	{name: 'Greenpoint', city_id: 4, borough: 'Brooklyn'},
	{name: 'Greenwood Heights', city_id: 4, borough: 'Brooklyn'},
	{name: 'Manhattan Beach', city_id: 4, borough: 'Brooklyn'},
	{name: 'Marine Park', city_id: 4, borough: 'Brooklyn'},
	{name: 'Midwood', city_id: 4, borough: 'Brooklyn'},
	{name: 'Mill Basin', city_id: 4, borough: 'Brooklyn'},
	{name: 'Park Slope', city_id: 4, borough: 'Brooklyn'},
	{name: 'Prospect Heights', city_id: 4, borough: 'Brooklyn'},
	{name: 'Prospect Park South/Kensington', city_id: 4, borough: 'Brooklyn'},
	{name: 'Rood Hook', city_id: 4, borough: 'Brooklyn'},
	{name: 'Sea Gate', city_id: 4, borough: 'Brooklyn'},
	{name: 'Sheepshead Bay', city_id: 4, borough: 'Brooklyn'},
	{name: 'Sunset Park', city_id: 4, borough: 'Brooklyn'},
	{name: 'Williamsburg', city_id: 4, borough: 'Brooklyn'},
	{name: 'Windsor Terrace', city_id: 4, borough: 'Brooklyn'},

	# Queens
	{name: 'Arverne', city_id: 4, borough: 'Queens'},
	{name: 'Astoria', city_id: 4, borough: 'Queens'},
	{name: 'Bayside', city_id: 4, borough: 'Queens'},
	{name: 'Beechhurst', city_id: 4, borough: 'Queens'},
	{name: 'Belle Harbor/Neponsit', city_id: 4, borough: 'Queens'},
	{name: 'Bellerose', city_id: 4, borough: 'Queens'},
	{name: 'Briarwood', city_id: 4, borough: 'Queens'},
	{name: 'Broad Channel', city_id: 4, borough: 'Queens'},
	{name: 'Cambria Heights', city_id: 4, borough: 'Queens'},
	{name: 'College Point', city_id: 4, borough: 'Queens'},
	{name: 'Corona', city_id: 4, borough: 'Queens'},
	{name: 'Douglaston', city_id: 4, borough: 'Queens'},
	{name: 'East Elmhurst', city_id: 4, borough: 'Queens'},
	{name: 'Elmhurst', city_id: 4, borough: 'Queens'},
	{name: 'Far Rockaway', city_id: 4, borough: 'Queens'},
	{name: 'Floral Park', city_id: 4, borough: 'Queens'},
	{name: 'Flushing', city_id: 4, borough: 'Queens'},
	{name: 'Forest Hills', city_id: 4, borough: 'Queens'},
	{name: 'Fresh Meadows', city_id: 4, borough: 'Queens'},
	{name: 'Glen Oaks', city_id: 4, borough: 'Queens'},
	{name: 'Glendale', city_id: 4, borough: 'Queens'},
	{name: 'Hillcrest', city_id: 4, borough: 'Queens'},
	{name: 'Hollis', city_id: 4, borough: 'Queens'},
	{name: 'Hollis Hills', city_id: 4, borough: 'Queens'},
	{name: 'Howard Beach', city_id: 4, borough: 'Queens'},
	{name: 'Jackson Heights', city_id: 4, borough: 'Queens'},
	{name: 'Jamaica', city_id: 4, borough: 'Queens'},
	{name: 'Jamaica Heights', city_id: 4, borough: 'Queens'},
	{name: 'Jamaica Hills', city_id: 4, borough: 'Queens'},
	{name: 'Kew Gardens', city_id: 4, borough: 'Queens'},
	{name: 'Laurelton', city_id: 4, borough: 'Queens'},
	{name: 'Little Neck', city_id: 4, borough: 'Queens'},
	{name: 'Long Island City', city_id: 4, borough: 'Queens'},
	{name: 'Maspeth', city_id: 4, borough: 'Queens'},
	{name: 'Middle Village', city_id: 4, borough: 'Queens'},
	{name: 'Oakland Gardens', city_id: 4, borough: 'Queens'},
	{name: 'Ozone Park', city_id: 4, borough: 'Queens'},
	{name: 'Queens Village', city_id: 4, borough: 'Queens'},
	{name: 'Rego Park', city_id: 4, borough: 'Queens'},
	{name: 'Richmond Hill', city_id: 4, borough: 'Queens'},
	{name: 'Ridgewood', city_id: 4, borough: 'Queens'},
	{name: 'Rockaway Park', city_id: 4, borough: 'Queens'},
	{name: 'Rosedale', city_id: 4, borough: 'Queens'},
	{name: 'South Jamaica', city_id: 4, borough: 'Queens'},
	{name: 'South Ozone Park', city_id: 4, borough: 'Queens'},
	{name: 'Springfield Gardens', city_id: 4, borough: 'Queens'},
	{name: 'St. Albans', city_id: 4, borough: 'Queens'},
	{name: 'Sunnyside', city_id: 4, borough: 'Queens'},
	{name: 'Whitestone', city_id: 4, borough: 'Queens'},
	{name: 'Woodhaven', city_id: 4, borough: 'Queens'},
	{name: 'Woodside', city_id: 4, borough: 'Queens'},

	# Staten Island
	{name: 'Annadale', city_id: 4, borough: 'Staten Island'},
	{name: 'Arden Heights', city_id: 4, borough: 'Staten Island'},
	{name: 'Arrochar', city_id: 4, borough: 'Staten Island'},
	{name: 'Bay Street', city_id: 4, borough: 'Staten Island'},
	{name: 'Bulls Head', city_id: 4, borough: 'Staten Island'},
	{name: 'Castleton Corners', city_id: 4, borough: 'Staten Island'},
	{name: 'Charleston', city_id: 4, borough: 'Staten Island'},
	{name: 'Clifton', city_id: 4, borough: 'Staten Island'},
	{name: 'Dongan Hills', city_id: 4, borough: 'Staten Island'},
	{name: 'Eltingville', city_id: 4, borough: 'Staten Island'},
	{name: 'Emerson Hill', city_id: 4, borough: 'Staten Island'},
	{name: 'Graniteville', city_id: 4, borough: 'Staten Island'},
	{name: 'Grant City', city_id: 4, borough: 'Staten Island'},
	{name: 'Grasmere/Concord', city_id: 4, borough: 'Staten Island'},
	{name: 'Great Kills', city_id: 4, borough: 'Staten Island'},
	{name: 'Grymes Hill', city_id: 4, borough: 'Staten Island'},
	{name: 'Huguenot', city_id: 4, borough: 'Staten Island'},
	{name: 'Livingston', city_id: 4, borough: 'Staten Island'},
	{name: 'Manor Heights', city_id: 4, borough: 'Staten Island'},
	{name: 'Mariners Harbor', city_id: 4, borough: 'Staten Island'},
	{name: 'Midland Beach', city_id: 4, borough: 'Staten Island'},
	{name: 'New Brighton', city_id: 4, borough: 'Staten Island'},
	{name: 'New Dorp/New Dorp Beach', city_id: 4, borough: 'Staten Island'},
	{name: 'New Springfield', city_id: 4, borough: 'Staten Island'},
	{name: 'Oakwood', city_id: 4, borough: 'Staten Island'},
	{name: 'Pleasant Plains', city_id: 4, borough: 'Staten Island'},
	{name: 'Port Richmond', city_id: 4, borough: 'Staten Island'},
	{name: 'Prince\'s Bay', city_id: 4, borough: 'Staten Island'},
	{name: 'Richmondtown', city_id: 4, borough: 'Staten Island'},
	{name: 'Rosebank', city_id: 4, borough: 'Staten Island'},
	{name: 'Rossville', city_id: 4, borough: 'Staten Island'},
	{name: 'Shore Acres', city_id: 4, borough: 'Staten Island'},
	{name: 'Silver Lake', city_id: 4, borough: 'Staten Island'},
	{name: 'South Beach', city_id: 4, borough: 'Staten Island'},
	{name: 'St. George', city_id: 4, borough: 'Staten Island'},
	{name: 'Stapleton', city_id: 4, borough: 'Staten Island'},
	{name: 'Sunnyside', city_id: 4, borough: 'Staten Island'},
	{name: 'Todt Hill', city_id: 4, borough: 'Staten Island'},
	{name: 'Tompkinsville', city_id: 4, borough: 'Staten Island'},
	{name: 'Tottenville', city_id: 4, borough: 'Staten Island'},
	{name: 'Travis', city_id: 4, borough: 'Staten Island'},
	{name: 'West New Brighton', city_id: 4, borough: 'Staten Island'},
	{name: 'Westerleigh', city_id: 4, borough: 'Staten Island'},
	{name: 'Willowbrook', city_id: 4, borough: 'Staten Island'},
	{name: 'Woodrow', city_id: 4, borough: 'Staten Island'},

	#LA
	{name: 'Angelino Heights', city_id: 1, borough: nil},
	{name: 'Arleta', city_id: 1, borough: nil},
	{name: 'Arlington Heights', city_id: 1, borough: nil},
	{name: 'Arts District', city_id: 1, borough: nil},
	{name: 'Atwater Village', city_id: 1, borough: nil},
	{name: 'Bladwin Hills', city_id: 1, borough: nil},
	{name: 'Bladwin Village', city_id: 1, borough: nil},
	{name: 'Bladwin Vista', city_id: 1, borough: nil},
	{name: 'Beachwood Canyon', city_id: 1, borough: nil},
	{name: 'Bel-Air', city_id: 1, borough: nil},
	{name: 'Benedict Canyon', city_id: 1, borough: nil},
	{name: 'Berkeley Square', city_id: 1, borough: nil},
	{name: 'Beverly Crest', city_id: 1, borough: nil},
	{name: 'Beverly Glen', city_id: 1, borough: nil},
	{name: 'Beverly Grove', city_id: 1, borough: nil},
	{name: 'Beverly Hills', city_id: 1, borough: nil},
	{name: 'Beverly Park', city_id: 1, borough: nil},
	{name: 'Beverlywood', city_id: 1, borough: nil},
	{name: 'Boyle Heights', city_id: 1, borough: nil},
	{name: 'Brentwood', city_id: 1, borough: nil},
	{name: 'Brentwood Circle', city_id: 1, borough: nil},
	{name: 'Brentwood Glen', city_id: 1, borough: nil},
	{name: 'Broadway-Manchester', city_id: 1, borough: nil},
	{name: 'Brookside', city_id: 1, borough: nil},
	{name: 'Bunker Hill', city_id: 1, borough: nil},
	{name: 'Cahuenga Pass', city_id: 1, borough: nil},
	{name: 'Canoga Park', city_id: 1, borough: nil},
	{name: 'Canterbury Knolls', city_id: 1, borough: nil},
	{name: 'Carthay', city_id: 1, borough: nil},
	{name: 'Castle Heights', city_id: 1, borough: nil},
	{name: 'Central-Alameda', city_id: 1, borough: nil},
	{name: 'Central City', city_id: 1, borough: nil},
	{name: 'Century City', city_id: 1, borough: nil},
	{name: 'Chatsworth', city_id: 1, borough: nil},
	{name: 'Chesterfield Square', city_id: 1, borough: nil},
	{name: 'Cheviot Hills', city_id: 1, borough: nil},
	{name: 'Chinatown', city_id: 1, borough: nil},
	{name: 'Civic Center', city_id: 1, borough: nil},
	{name: 'Crenshaw', city_id: 1, borough: nil},
	{name: 'Crestwood Hills', city_id: 1, borough: nil},
	{name: 'Cypress Park', city_id: 1, borough: nil},
	{name: 'Del Rey', city_id: 1, borough: nil},
	{name: 'Downtown', city_id: 1, borough: nil},
	{name: 'Eagle Rock', city_id: 1, borough: nil},
	{name: 'East Gate Bel Air', city_id: 1, borough: nil},
	{name: 'East Hollywood', city_id: 1, borough: nil},
	{name: 'Echo Park', city_id: 1, borough: nil},
	{name: 'Edendale', city_id: 1, borough: nil},
	{name: 'El Sereno', city_id: 1, borough: nil},
	{name: 'Elysian Heights', city_id: 1, borough: nil},
	{name: 'Elysian Park', city_id: 1, borough: nil},
	{name: 'Elysian Valley', city_id: 1, borough: nil},
	{name: 'Encino', city_id: 1, borough: nil},
	{name: 'Exposition Park', city_id: 1, borough: nil},
	{name: 'Faircrest Heights', city_id: 1, borough: nil},
	{name: 'Fairfax', city_id: 1, borough: nil},
	{name: 'Fashion District', city_id: 1, borough: nil},
	{name: 'Filipinotown', city_id: 1, borough: nil},
	{name: 'Financial District', city_id: 1, borough: nil},
	{name: 'Florence', city_id: 1, borough: nil},
	{name: 'Flower District', city_id: 1, borough: nil},
	{name: 'Franklin Hills', city_id: 1, borough: nil},
	{name: 'Gallery Row', city_id: 1, borough: nil},
	{name: 'Garvanza', city_id: 1, borough: nil},
	{name: 'Glassell Park', city_id: 1, borough: nil},
	{name: 'Gramercy Park', city_id: 1, borough: nil},
	{name: 'Granada Hills', city_id: 1, borough: nil},
	{name: 'Green Meadows', city_id: 1, borough: nil},
	{name: 'Griffith Park', city_id: 1, borough: nil},
	{name: 'Hancock Park', city_id: 1, borough: nil},
	{name: 'Harbor City', city_id: 1, borough: nil},
	{name: 'Harbor Gateway', city_id: 1, borough: nil},
	{name: 'Harvard Heights', city_id: 1, borough: nil},
	{name: 'Harvard Park', city_id: 1, borough: nil},
	{name: 'Hermon', city_id: 1, borough: nil},
	{name: 'Highland Park', city_id: 1, borough: nil},
	{name: 'Historic Core', city_id: 1, borough: nil},
	{name: 'Hollywood', city_id: 1, borough: nil},
	{name: 'Hollywood Dell', city_id: 1, borough: nil},
	{name: 'Hollywood Hills', city_id: 1, borough: nil},
	{name: 'Holmby Hills', city_id: 1, borough: nil},
	{name: 'Hyde Park', city_id: 1, borough: nil},
	{name: 'Jefferson Park', city_id: 1, borough: nil},
	{name: 'Jewelry District', city_id: 1, borough: nil},
	{name: 'Kinney Heights', city_id: 1, borough: nil},
	{name: 'Koreatown', city_id: 1, borough: nil},
	{name: 'Ladera', city_id: 1, borough: nil},
	{name: 'Lafayette Square', city_id: 1, borough: nil},
	{name: 'Lake Balboa', city_id: 1, borough: nil},
	{name: 'Lake View Terrace', city_id: 1, borough: nil},
	{name: 'Larchmont', city_id: 1, borough: nil},
	{name: 'Laurel Canyon', city_id: 1, borough: nil},
	{name: 'Leimert Park', city_id: 1, borough: nil},
	{name: 'Lincoln Heights', city_id: 1, borough: nil},
	{name: 'Little Armenia', city_id: 1, borough: nil},
	{name: 'Little Ethiopia', city_id: 1, borough: nil},
	{name: 'Little Tokyo', city_id: 1, borough: nil},
	{name: 'Los Feliz', city_id: 1, borough: nil},

])